import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.page}>
        <Image className={styles.bgImage} src="/mountain_bg.png" alt="Background mountain image." layout="fill" />

        <nav>
          <ul>
            <li>Portfolio</li>
            <li>Contact</li>
            <li>Resume</li>
          </ul>
        </nav>

        <h1>Hi, I&apos;m Nick Burt</h1>
        <p>
          I am a full stack web developer. I have a passion for creating beautiful
          and responsive web applications, powered by scalable web servers and databases.
        </p>
        <p>Javascript - React - Node - MongoDB - MySQL</p>
      </main>
    </div>
  );
}
