import Head from 'next/head';
import styles from '../styles/Home.module.scss';

// Components
import { NavigationBar } from '../components/NavigationBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.page}>
        <NavigationBar />

        <h1>Hi, I&apos;m Nick Burt</h1>

        <section className={styles.content}>
          <p>
            I am a full stack web developer. I have a passion for creating beautiful
            and responsive web applications, powered by scalable web servers and databases.
          </p>
          <hr />
          <p>Javascript - React - Node - MongoDB - MySQL</p>
        </section>
      </main>
    </div>
  );
}
